### ISSUE TITLE
Show more score results

### ISSUE THREAD

**Issue by MichalSkoula** [MichalSkoula/arco-1500#10]

**Comment by MichalSkoula** [comment]
@ddonatek Houston, we have a problem

![IMG_20190413_215300](https://user-images.githubusercontent.com/5922575/56084713-3bbd8880-5e37-11e9-933e-7fc8ff213b07.jpg)

**Comment by ddonatek** [comment]
fixed 13488a0c6a1a3e93ccddaebf43cec5b226dbed5d
