### ISSUE TITLE
emulátor David re-PIN hell ride

### ISSUE THREAD

**Issue by MichalSkoula** [MichalSkoula/arco-1500#13]
_kromě toho, že musím přepojit drátky (tipuju tak rok), tak musím opravit v not_emulator (1 minuta)_

then, merge uno_version

**Comment by MichalSkoula** [comment]
come on @ddonatek

**Comment by ddonatek** [comment]
done cd1bdf321717a74283c3ce773f1ac687dd5bc8fd
