### ISSUE TITLE
Score eraser

### ISSUE THREAD

**Issue by MichalSkoula** [MichalSkoula/arco-1500#15]
There will be a game called _eraser. Once uploaded, it should erase whole EEPROM memory and print some OK message.

Because after I fucked up score, I am no longer able to see numbers...only order. I think this Is because od cripled EEPROM every 22th byte thing.

**Comment by MichalSkoula** [comment]
Score will be erased after holding action button for 2 seconds.

**Comment by MichalSkoula** [comment]
@ddonatek 💻

**Comment by ddonatek** [comment]
added in ae991fa22097dc9d569a889d342527e34b511bfd

(not tested in arduino, but i'm sure it's flawless)

**Comment by MichalSkoula** [comment]
@ddonatek  👍 👍 👍
